### ISSUE TITLE
A little repo cleanup

### ISSUE THREAD

**Issue by ccurtis7** [ZaneDaPayne/Domino_App_Project#6]
A few items to keep your repo tidy:

The `.ipynb_checkpoints` is unnecessary metadata, files that are autmatically created as a form of backup. They are OK to store on your local machine, but shouldn't be pushed to your online repo. I suggest adding `.ipynb_checkpoints` to your `.ignore` file so they don't ever get pushed accidentally.

I would also reserve a single folder to contain all your image data. There are quite a few folders of images in your first directory level. You can move them to a sub-folder within your repository instead.

**Comment by ZaneDaPayne** [comment]
The .ipynp file has been removed and that extension has been added to the .gitignore file. All images have been moved to the images folder.
