### ISSUE TITLE
Consider storing images elsewhere

### ISSUE THREAD

**Issue by ccurtis7** [ZaneDaPayne/Domino_App_Project#8]
Your images are probably fairly small, but it usually isn't a good idea to store all your image data with your code in a GitHub repository. The two main reasons are (1) you risk running up against the max storage capacity GitHub allows in a repo and (2) you may have data you don't want to share with the world. 

Typically, you may store a few sample images in your repo (think how `skimage` works-- they provide a few sample images for you to play around with). For working with your team and developing your code with your image datasets, you can store your data in a shared location where teammate can access. I recommend your Google Drive, as students have unlimited space.

**Comment by Hkethar** [comment]
Stored images on student google drive account.
