### ISSUE TITLE
why the read latency for this code is 2+ hours after doing a convolution?

### ISSUE THREAD

**Issue by Hkethar** [ZaneDaPayne/Domino_App_Project#9]
image = img_as_float(im)
gamma_corrected = exposure.adjust_gamma(image, 10)
thresh = threshold_otsu(image)
        #Applying threshold
thresholded_image = image > thresh
        #Finds contour at certain values
contours = measure.find_contours(thresholded_image, 0.8)
fig, ax = plt.subplots()
ax.imshow(image, cmap=plt.cm.gray)
for n, contour in enumerate(contours):
    ax.plot(contour[:, 1], contour[:, 0], linewidth=2)
ax.axis('image')
ax.set_xticks([])
ax.set_yticks([])
plt.show()

**Comment by ZaneDaPayne** [comment]
For me it runs in under a second.
